package XBee.Configurator;

public enum MessageType {
	COORDINATOR_NOT_DETECTED, PAN_ID_OUT_OF_BOUNDS, TEXT_OUT_OF_BOUNDS, SET_SENSOR,
	REMOVE_SENSOR, SET_ACTUATOR, REMOVE_ACTUATOR, DEVICES_NOT_DETECTED, DEVICE_NOT_FOUND,
	PAN_ID_NOT_CHANGED, ADDRESS_NOT_ACCEPTABLE, ADDRESS_OUT_OF_BOUNDS, ADDRESS_SHORT_LENGTH,
	ACTUATORS_LIMIT_REACHED, SENSOR_LIMIT_REACHED
}